# config/packages/calliostro_spotify_web_api.yaml
calliostro_spotify_web_api:

  # Your Client ID
  client_id:            'ea1e63efacd041fcb13e0d9957de61a2' # Required

  # Your Client Secret
  client_secret:        'ac3a31b7569b480aa0cddf07b7099571' # Required

  # Options for SpotifyWebAPI client
  # https://github.com/jwilsson/spotify-web-api-php/blob/main/docs/examples/setting-options.md
  options:
    auto_refresh:         false
    auto_retry:           false
    return_assoc:         false

  # Address to redirect to after authentication success OR failure
  redirect_uri:         '' # Example: 'https://127.0.0.1:8000/callback/'

  # Service ID of the token provider that provides the user's access token
  token_provider:       calliostro_spotify_web_api.token_provider